-- MySQL Script generated by MySQL Workbench
-- Fri Dec 22 21:46:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema joparkdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema joparkdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `joparkdb` DEFAULT CHARACTER SET utf8 ;
USE `joparkdb` ;

-- -----------------------------------------------------
-- Table `joparkdb`.`user_character_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_character_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_character_tbl` (
  `user_id` VARCHAR(45) NOT NULL,
  `quest_id` INT NULL COMMENT '연관 테이블 : 퀘스트(quest) 테이블, 사용자 퀘스트(user_quest) 테이블   - 현재 진행 중인 퀘스트를 사용자 퀘스트 테이블에서 가져온다.    - 사용자 퀘스트 정보는 퀘스트 테이블 정보에서 가져온다.',
  `pet_id_1` INT NULL,
  `pet_id_2` INT NULL,
  `pet_id_3` INT NULL,
  `pet_id_4` INT NULL,
  `pet_id_5` INT NULL,
  `pet_id_6` INT NULL,
  `slot_cnt` INT NULL COMMENT '인벤토리 최대 갯수',
  `level_id` INT NULL,
  `auth_id` VARCHAR(45) NULL COMMENT '접근권한 사용자권한관리(user_access_management)  관리자, 유저, 블럭 계정 관리',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
COMMENT = '사용자 캐릭터 정보';


-- -----------------------------------------------------
-- Table `joparkdb`.`user_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_manage_tbl` (
  `user_id` INT NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `birth` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cash` VARCHAR(45) NULL,
  `rank` VARCHAR(45) NULL COMMENT '유저 (대전) 랭킹 ',
  `password` VARCHAR(45) NULL,
  `user_name` VARCHAR(45) NULL)
ENGINE = InnoDB
COMMENT = '사용자 정보';


-- -----------------------------------------------------
-- Table `joparkdb`.`pet_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`pet_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`pet_manage_tbl` (
  `pet_id` INT NOT NULL,
  `pet_cnt` VARCHAR(45) NULL,
  `pet_name` VARCHAR(45) NULL,
  `pet_level` VARCHAR(45) NULL,
  `pet_type` VARCHAR(45) NULL,
  `pet_hp` VARCHAR(45) NULL,
  `pet_mp` VARCHAR(45) NULL,
  `pet_skill_id` VARCHAR(45) NULL,
  `next_evolution_id` VARCHAR(45) NULL,
  `next_evolution_level` VARCHAR(45) NULL,
  `pet_attack` VARCHAR(45) NULL,
  `pet_defense` VARCHAR(45) NULL,
  `pet_speed` VARCHAR(45) NULL,
  PRIMARY KEY (`pet_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`user_pets_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_pets_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_pets_tbl` (
  `user_pet_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `pet_id` VARCHAR(45) NULL,
  `user_pet_level` VARCHAR(45) NULL,
  `user_pet_exp` VARCHAR(45) NULL,
  `user_pet_status` VARCHAR(45) NULL COMMENT '펫 상태 (ex : 기절, 독, 화상 등등)',
  `user_pet_max_skill` VARCHAR(45) NULL,
  PRIMARY KEY (`user_pet_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`user_pet_skill_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_pet_skill_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_pet_skill_tbl` (
  `uset_pet_skill_id` INT NOT NULL,
  `user_pet_id` VARCHAR(45) NULL,
  `skill_id` VARCHAR(45) NULL,
  PRIMARY KEY (`uset_pet_skill_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`user_pet_equip_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_pet_equip_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_pet_equip_tbl` (
  `user_pet_equip_id` INT NOT NULL,
  `user_pet_id` VARCHAR(45) NULL,
  `ak_item_id` VARCHAR(45) NULL COMMENT '공격력 장비',
  `df_item_id` VARCHAR(45) NULL COMMENT '방어력 장비',
  PRIMARY KEY (`user_pet_equip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`skill_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`skill_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`skill_manage_tbl` (
  `skill_id` INT NOT NULL,
  `skill_name` VARCHAR(45) NULL,
  `type_id` VARCHAR(45) NULL,
  `skill_speed` VARCHAR(45) NULL COMMENT '스킬 우선 순위',
  `skill_damage_code` VARCHAR(45) NULL COMMENT '타격 구분(hp, mp)',
  `skill_damage_value` VARCHAR(45) NULL COMMENT '스킬 공격 수치',
  `skill_drain_code` VARCHAR(45) NULL COMMENT '흡수 타입 구분(hp, mp)',
  `skill_drain_value` VARCHAR(45) NULL COMMENT '흡수 수치',
  `skill_spend_code` VARCHAR(45) NULL COMMENT '스킬 구분(hp, mp)',
  `skill_spend_value` VARCHAR(45) NULL COMMENT '소모 mp',
  PRIMARY KEY (`skill_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`type_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`type_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`type_manage_tbl` (
  `type_id` INT NOT NULL,
  `type_name` VARCHAR(45) NULL,
  `type_desc` VARCHAR(45) NULL,
  `type_code` VARCHAR(45) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB
COMMENT = '속성 관리 테이블';


-- -----------------------------------------------------
-- Table `joparkdb`.`quest_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`quest_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`quest_manage_tbl` (
  `quest_id` INT NOT NULL,
  `reward_id` VARCHAR(45) NULL,
  `quest_name` VARCHAR(45) NULL COMMENT '퀘스트 이름',
  `quest_next_id` INT NULL COMMENT '다음 퀘스트 id',
  `quest_level` VARCHAR(45) NULL COMMENT '퀘스트 수행 제한 레벨',
  `quest_yn` INT NULL,
  `quest_class` VARCHAR(45) NULL COMMENT '메인 : m 서브 : s  필드 명 ',
  PRIMARY KEY (`quest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`reward_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`reward_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`reward_manage_tbl` (
  `reward_id` INT NOT NULL COMMENT '1. quest_manage_tbl.  2.battle_cpu_manage_tbl',
  `items_id` VARCHAR(45) NULL COMMENT '배열로 처리. 다수의 아이템정보를 담기 위함.',
  `reward_gold` VARCHAR(45) NULL COMMENT '보상 돈',
  `reward_exp` VARCHAR(45) NULL COMMENT '험치',
  `category_code` VARCHAR(45) NULL COMMENT '보상 구분 Ex) 퀘스트, CPU전투, 레벨업, ...',
  PRIMARY KEY (`reward_id`))
ENGINE = InnoDB
COMMENT = '보상 관리';


-- -----------------------------------------------------
-- Table `joparkdb`.`user_quest_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_quest_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_quest_manage_tbl` (
  `user_id` INT NULL,
  `quest_id` INT NULL,
  `user_quest_status` VARCHAR(45) NULL COMMENT '퀘스트 진행 상태  수행 전 :  수행 중 : 수행 완료 :  ',
  `user_quest_cnt` VARCHAR(45) NULL COMMENT '최대 퀘스트 보유 수 ')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`level_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`level_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`level_manage_tbl` (
  `level_id` INT NOT NULL,
  `need_exp` VARCHAR(45) NULL,
  `level` VARCHAR(45) NULL,
  `target_code` VARCHAR(45) NULL COMMENT '유저 : u 펫 : p ',
  PRIMARY KEY (`level_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`user_item_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_item_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_item_tbl` (
  `user_id` INT NOT NULL,
  `item_id` VARCHAR(45) NULL,
  `item_cnt` VARCHAR(45) NULL,
  `input_date` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`item_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`item_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`item_manage_tbl` (
  `item_id` INT NOT NULL,
  `item_attack_point` VARCHAR(45) NULL,
  `item_defence_point` VARCHAR(45) NULL,
  `item_desc` VARCHAR(45) NULL,
  `item_name` VARCHAR(45) NULL,
  `item_hp` VARCHAR(45) NULL,
  `item_mp` VARCHAR(45) NULL,
  `item_speed` VARCHAR(45) NULL,
  `item_purchase_price` VARCHAR(45) NULL,
  `item_sale_price` VARCHAR(45) NULL,
  `type_id` VARCHAR(45) NULL,
  `item_class` VARCHAR(45) NULL COMMENT '추후 논의 필요 소모품 :  장비 : ',
  `item_cash_price` VARCHAR(45) NULL,
  `access_lvl` VARCHAR(45) NULL COMMENT '장착레벨제한',
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`user_cash_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_cash_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_cash_tbl` (
  `cash_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `item_id` VARCHAR(45) NULL,
  `purchase_date` VARCHAR(45) NULL COMMENT '구입 날짜',
  `purchase_status` VARCHAR(45) NULL COMMENT '환불 처리 여부 사용 여부',
  `payment_id` VARCHAR(45) NULL,
  PRIMARY KEY (`cash_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`payment_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`payment_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`payment_manage_tbl` (
  `payment_id` INT NOT NULL,
  `payment_phone` VARCHAR(45) NULL COMMENT '핸드폰 결제',
  `payment_card` VARCHAR(45) NULL COMMENT '카드 결제',
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`npc_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`npc_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`npc_manage_tbl` (
  `npc_id` INT NOT NULL,
  `npc_name` VARCHAR(45) NULL,
  `npc_talk_id` VARCHAR(45) NULL COMMENT '참조키. talk_manage_tbl.talk_id',
  `access_level` VARCHAR(45) NULL,
  PRIMARY KEY (`npc_id`))
ENGINE = InnoDB
COMMENT = 'NPC정보';


-- -----------------------------------------------------
-- Table `joparkdb`.`talk_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`talk_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`talk_manage_tbl` (
  `talk_id` INT NOT NULL,
  `quest_id` VARCHAR(45) NULL,
  `talk_content` VARCHAR(45) NULL COMMENT '- properties 파일에 존재하는 내용을 가져오기 위한 키값 저장',
  `talk_content_yes` VARCHAR(45) NULL COMMENT '- properties 파일에 존재하는 내용을 가져오기 위한 키값 저장 - yes누를 때의 스크립트 내용 불러오기',
  `talk_context_no` VARCHAR(45) NULL COMMENT '- properties 파일에 존재하는 내용을 가져오기 위한 키값 저장 - no누를 때의 스크립트 내용 저장',
  PRIMARY KEY (`talk_id`))
ENGINE = InnoDB
COMMENT = 'NPC대화내용';


-- -----------------------------------------------------
-- Table `joparkdb`.`user_battle_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`user_battle_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`user_battle_manage_tbl` (
  `user_battle_id` INT NOT NULL COMMENT '[기본키] 대전 id 사용자 id',
  `user_id` VARCHAR(45) NULL COMMENT '[참조키] user_character_tbl.user_id',
  `battle_id` VARCHAR(45) NULL COMMENT '[참조키] ',
  `opponent_id` VARCHAR(45) NULL COMMENT '대전 상대 ID',
  `bet_item_id` VARCHAR(45) NULL COMMENT '대전 내기 아이템 id',
  `win_cnt` VARCHAR(45) NULL COMMENT '승리 횟수',
  `lose_cnt` VARCHAR(45) NULL COMMENT '패배 횟수',
  `battle_user_yn` VARCHAR(45) NULL COMMENT '대전 상대 사용자인지 CPU 인지 정보 표시 플래그',
  `battle_date` VARCHAR(45) NULL COMMENT '대전일자',
  PRIMARY KEY (`user_battle_id`))
ENGINE = InnoDB
COMMENT = '사용자대전정보';


-- -----------------------------------------------------
-- Table `joparkdb`.`battle_room_info_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`battle_room_info_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`battle_room_info_tbl` (
  `battle_room_id` INT NOT NULL COMMENT '[기본키]',
  `battle_room_no` VARCHAR(45) NULL,
  `battle_use_item_yn` VARCHAR(45) NULL COMMENT '아이템전, 노템전 구분하는 플래그',
  `battle_bet_item_yn` VARCHAR(45) NULL COMMENT '대전 시 아이템 배팅 여부',
  `battle_status` VARCHAR(45) NULL COMMENT '현재 플레이중인지 플래그 표시',
  `limit_user_cnt` VARCHAR(45) NULL COMMENT '사용자 제한 수',
  `battle_name` VARCHAR(45) NULL COMMENT '대전방 제목',
  PRIMARY KEY (`battle_room_id`))
ENGINE = InnoDB
COMMENT = '대전방정보';


-- -----------------------------------------------------
-- Table `joparkdb`.`battle_room_user_info_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`battle_room_user_info_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`battle_room_user_info_tbl` (
  `user_id` INT NOT NULL,
  `battle_room_id` VARCHAR(45) NULL COMMENT '[참조키] battle_room_info_tbl.battle_room_id',
  `ready_yn` VARCHAR(45) NULL COMMENT '레디 했는지 여부',
  `bet_item_id` VARCHAR(45) NULL COMMENT '배팅한 아이템 id',
  `team_code` VARCHAR(45) NULL COMMENT '무슨 팀인지',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
COMMENT = '대전방 사용자 정보관리';


-- -----------------------------------------------------
-- Table `joparkdb`.`place_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`place_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`place_manage_tbl` (
  `place_id` INT NOT NULL COMMENT '[기본키]  Place_id : A - 레벨제한 : 5 Place_id : B - 레벨제한 : 5 둘다 입장가능?',
  `place_code` VARCHAR(45) NULL COMMENT '장소구분 코드 맵 노출 가중치를 두기 위함',
  `place_name` VARCHAR(45) NULL COMMENT '장소 이름',
  `type_id` VARCHAR(45) NULL COMMENT '[참조키] type_manage_tbl.type_id',
  `access_lvl` VARCHAR(45) NULL COMMENT '접근제한 레벨',
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB
COMMENT = '장소 정보';


-- -----------------------------------------------------
-- Table `joparkdb`.`battle_cpu_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`battle_cpu_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`battle_cpu_manage_tbl` (
  `cpu_id` INT NOT NULL COMMENT '[기본키]',
  `difficulty_code` VARCHAR(45) NULL COMMENT '난이도 코드',
  `cpu_level` VARCHAR(45) NULL,
  `reward_id` VARCHAR(45) NULL COMMENT '[참조키] reward_manage_tbl.reward_id',
  PRIMARY KEY (`cpu_id`))
ENGINE = InnoDB
COMMENT = '상대 CPU 정보';


-- -----------------------------------------------------
-- Table `joparkdb`.`notice_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`notice_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`notice_tbl` (
  `notice_id` INT NOT NULL COMMENT '[기본키]',
  `title` VARCHAR(45) NULL COMMENT '제목',
  `author` VARCHAR(45) NULL COMMENT '작성자',
  `context` VARCHAR(45) NULL COMMENT '본문',
  `input_date` DATETIME NULL COMMENT '작성일자',
  `file_id` VARCHAR(45) NULL COMMENT '[참조키] notice_file_manage_tbl.file_id',
  PRIMARY KEY (`notice_id`))
ENGINE = InnoDB
COMMENT = '공지사항 게시판';


-- -----------------------------------------------------
-- Table `joparkdb`.`notice_file_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`notice_file_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`notice_file_manage_tbl` (
  `file_id` INT NOT NULL COMMENT '[기본키] ',
  `file_name` VARCHAR(45) NULL COMMENT '파일명',
  `notice_id` VARCHAR(45) NULL COMMENT '[참조키] notice_tbl.notice_id',
  `file_ori_name` VARCHAR(45) NULL COMMENT '파일원본이름',
  `file_chan_name` VARCHAR(45) NULL COMMENT '파일변경이름',
  PRIMARY KEY (`file_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joparkdb`.`auth_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`auth_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`auth_manage_tbl` (
  `auth_id` INT NOT NULL COMMENT '[기본키]',
  `desc` VARCHAR(45) NULL COMMENT '권한설명(사유)',
  `ben_period` VARCHAR(45) NULL COMMENT '정지기간',
  PRIMARY KEY (`auth_id`))
ENGINE = InnoDB
COMMENT = '사용자 접근권한 ex)계정 정지, ...';


-- -----------------------------------------------------
-- Table `joparkdb`.`buddy_manage_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joparkdb`.`buddy_manage_tbl` ;

CREATE TABLE IF NOT EXISTS `joparkdb`.`buddy_manage_tbl` (
  `user_id` INT NOT NULL,
  `buddy_id` VARCHAR(45) NULL COMMENT '[참조키] user_manage_tbl.user_id',
  `blind_id` VARCHAR(45) NULL COMMENT '[참조키] user_manage_tbl.user_id',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
